version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: tododb
      DB_SSLMODE: disable
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db

  test:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: tododb
      DB_SSLMODE: disable
    depends_on:
      - db
    command: sh -c "/wait-for-postgres.sh db go test ./tests"
